version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka
  kafka:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    links:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka
  rest:
    image: confluentinc/cp-kafka-rest
    depends_on:
      - zookeeper
      - kafka
      - registry
    links:
      - zookeeper
      - kafka
      - registry
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_REST_HOST_NAME: rest
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://registry:8081
    networks:
      - kafka
  registry:
    image: confluentinc/cp-schema-registry
    depends_on:
      - kafka
      - zookeeper
    links:
      - kafka
      - zookeeper
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_HOST_NAME: registry
    networks:
      - kafka
  proxy:
    image: nginx:1.13
    depends_on:
      - rest
    links:
      - rest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - kafka
networks:
  kafka:
